# Generated by Django 5.0.3 on 2024-03-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kani', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Geeks',
            new_name='InfoUser',
        ),
    ]
