# Generated by Django 5.0.3 on 2024-03-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kani', '0004_alter_infouser_options_infouser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='facebook',
            field=models.URLField(default=1, max_length=255, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='instagram',
            field=models.URLField(default=1, max_length=255, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='locate',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Телофонный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='work',
            field=models.CharField(default=1, max_length=255, verbose_name='Профессия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='youtube',
            field=models.URLField(default=1, max_length=255, verbose_name='Youtube'),
            preserve_default=False,
        ),
    ]
