# Generated by Django 5.0.3 on 2024-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kani', '0005_infouser_email_infouser_facebook_infouser_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Youtube'),
        ),
    ]
