# Generated by Django 5.0.3 on 2024-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kani', '0006_alter_infouser_facebook_alter_infouser_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='secondary/', verbose_name='Фото пользователя')),
                ('tittle', models.CharField(max_length=255, verbose_name='Коротко о себе')),
                ('description', models.CharField(max_length=255, verbose_name='О Себе')),
            ],
            options={
                'verbose_name': 'О пользователе',
                'verbose_name_plural': 'О пользователей',
            },
        ),
        migrations.AddField(
            model_name='infouser',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='froms',
            field=models.CharField(default=1, max_length=255, verbose_name='Откуда'),
            preserve_default=False,
        ),
    ]
