# Generated by Django 5.0.3 on 2024-03-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kani', '0007_secondary_infouser_age_infouser_froms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary',
            name='description',
            field=models.TextField(max_length=255, verbose_name='О Себе'),
        ),
    ]
